### ISSUE TITLE
Explorer does not re-open with the "Uninstall OneDrive" option.

### ISSUE THREAD

**Issue by MichelePipi** [WinTweakers/WindowsToolbox#6]
When using the "Uninstall OneDrive" option with WindowsToolBox RC-3, explorer remains closed and does not re-open.

**Comment by khanhmuy** [comment]
oop- *edit: weird it works normal for me*

**Comment by CallMeEchoCodes** [comment]
@AvaaaUwU what windows build are you on. This can be found by running `winver`.
![image](https://user-images.githubusercontent.com/36752347/126450256-4feafd4f-4de2-442d-90c9-63c4df33f04f.png)
you are looking for os build.

**Comment by MichelePipi** [comment]
![image](https://user-images.githubusercontent.com/80199022/126479922-c4eb9549-3ecc-4684-8554-431849c1005a.png)

**Comment by CallMeEchoCodes** [comment]
fixed in c4e13cb
