### ISSUE TITLE
This software secretly installs Malware

### ISSUE THREAD

**Issue by slysnake96** [WinTweakers/WindowsToolbox#8]
It just so happens that this software secretly installs Malware.
LTT covered this recently in his latest TechLinked episode 16/04/2022.
Here is the exact episode.
https://youtu.be/AEuSYBJLYlY?t=313

**Comment by khanhmuy** [comment]
Man... at least watch the video carefully before saying, you got the wrong toolbox, ours don't even have the function to install Play Store. Besides, it's literally just a bunch of PS scripts, if you want you can go check the files out yourself.
![image](https://user-images.githubusercontent.com/66995788/163672611-4ea33bbe-6a5f-43df-9aba-90a424c3f1a6.png)
THE DAMM README IS DIFFERENT
